name: Test

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build Target'
        required: true

env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  RClone_Config: ${{ secrets.RClone_Config }}
  partialTarget: ${{ github.event.inputs.target }}
  TZ: Asia/Dhaka

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Increase Swap Space
        run: ./setSwap.sh 13G
      - name: Setup Git Auth & repo binary
        run: ./gitAuth.sh
      - name: Cleanup Space
        run: curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash
      - name: Sync git-repo
        run: ./repoSync.sh
      - name: Setup Build Environment
        run: ./setEnv.sh
      - name: Get ccache
        run: ./ccashier.sh download || true
      - name: Partial Build ${{ env.partialTarget }}
        timeout-minutes: 320
        run: |
          echo "Building for ${{ env.partialTarget }}"
          ./partialBuild.sh ${{ env.partialTarget }}
      - name: Upload ccache
        continue-on-error: true
        run: ./ccashier.sh upload
